// <auto-generated />
namespace GamerHQ_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddingCrossplayOption : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingCrossplayOption));
        
        string IMigrationMetadata.Id
        {
            get { return "202105131730245_AddingCrossplayOption"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
